name: Deploy alxmultimedia

on:
  push:
    branches:
      - dev
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to dev
      if: github.ref == 'refs/heads/dev'
      run: |
        rsync -avz --delete ./ ${{ vars.DEPLOY_DIRECTORY }}

    - name: Deploy to prod
      if: github.ref == 'refs/heads/master'
      run: |
        rsync -avz --delete ./ ${{ vars.DEPLOY_DIRECTORY }}
